# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MYiMei' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MYiMei

  target 'MYiMeiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MYiMeiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Then'
pod 'SnapKit', '~> 5.0.0'
pod 'Moya','12.0.1'
pod 'HandyJSON','5.0.0-beta'
pod 'Kingfisher'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'Reusable'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'KMPlaceholderTextView', '~> 1.4.0'
pod 'BSImagePicker', '~> 2.10.0'

end
